### ISSUE TITLE
Add a contributors guide

### ISSUE THREAD

**Issue by phutchins** [dcgtc/dgrants#31] opened 2021-07-21 15:17 UTC
We need to add a contributors guide to enable future contributions.

**Comment by apbendi** [comment] 2021-08-02 22:21
When this get's done, can we be sure to include the following content about the Rebase workflow.

dGrants follows a rebase workflow, rather than a merge workflow. In brief, this means:

* Each new feature should be developed in an independent, short running branch

```bash
git checkout my-feature-branch
```

* The developer or developers working on said feature are responsible for keeping it up to date with `main`, that is, rebasing their branch to `main` as it evolves.

```bash
git checkout main
git pull origin main # get the latest
git checkout my-feature-branch
git rebase my-feature-branch main
```

* If conflicts are found, resolve them here. See [here](https://docs.github.com/en/get-started/using-git/resolving-merge-conflicts-after-a-git-rebase) for more info
* After rebasing, force push back to your feature branch, but *never* force push to `main`:

```bash
git push origin my-feature-branch --force
```

* Every PR merged should merged with GitHub's `Rebase and Merge` button, or with a fast-forward merge on command line, like:
 
```bash
git checkout main
git merge my-feature-branch --ff-only
git push origin HEAD
```

The advantages of this system are:

* Encourages short-running feature branches with fewer opportunities for merge conflicts
* Encourages the developer of the feature to be the one that resolves merge conflicts related to said feature, reducing the likelihood of a bug or regression slipping in due to conflict resolution
* Keeps commit history clean and easy to read

**Comment by mds1** [comment] 2021-08-02 22:59
> but _never_ force push to `main`

@phutchins @apbendi Should we make sure this is prevented by the repo settings?

**Comment by phutchins** [comment] 2021-08-03 11:34
> > but _never_ force push to `main`
> 
> @phutchins @apbendi Should we make sure this is prevented by the repo settings?

I'm torn on this because 99.9% of the time we don't want anyone to do this. There is however that one time when there is a good reason to force push to main. Let's add it with a way to bypass is necessary so that it catches the mistakes buy still allows us to use if necessary. If there is no way bypass we could work around the block when needed also.

**Comment by apbendi** [comment] 2021-08-03 18:32
> I'm torn on this because 99.9% of the time we don't want anyone to do this. There is however that one time when there is a good reason to force push to main. Let's add it with a way to bypass is necessary so that it catches the mistakes buy still allows us to use if necessary. If there is no way bypass we could work around the block when needed also.

I guess the "workaround" would be toggling the setting when needed, then toggling back afterwards. I think I'm in favor of turning it on for safety.

**Closed** 2021-08-12 08:26 UTC
